bugtracker/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('', include('main.urls')),
    path('admin/', admin.site.urls),
]

main/urls.py
from django.urls import path
from . import views

app_name = 'main'

urlpatterns = [
    path('', views.loginpage, name = 'loginpage'),

    # do not write name = logout as it'll override the default logout page
    path('logout', views.logoutpage, name = 'logoutpage'),

    path('issue/<int:project_id>/', views.issue, name = 'issue'),

    path('issues', views.issues, name = 'issues'),

    path('add_issue', views.add_issues, name = 'add_issues'),

    path('projects', views.projects, name = 'projects')

]

main/models.py
from django.db import models
import datetime
from django.contrib.auth.models import User, Group

class Tag(models.Model):
    name = models.CharField(max_length=30)

    def __str__(self):
        return self.name 

# class Feature(models.Model):
#     name = models.CharField(max_length=30)

#     def __str__(self):
#         return self.name

priority = [
    ('critical', 'critical'),
    ('high', 'high'),
    ('normal', 'normal'),
    ('low', 'low')
]

status = [
    ('open', 'open'),
    ('in progress', 'in progress'),
    ('resolved', 'resolved'),
    ('closed', 'closed'),
    ('duplicate', 'duplicate')
]




########################## Major models ############

class Project(models.Model):
    name = models.CharField(max_length=50)
    desc = models.CharField(max_length=250)
    start = models.DateField(default=datetime.date.today())
    end = models.DateField(null = True, blank = True)
    issues_open = models.IntegerField(null=False, blank=False, default=0)
    total_issues = models.IntegerField(null=False, blank=False, default=0)
    issues_closed = models.IntegerField(null=False, blank=False, default=0)
    project_manager = models.ForeignKey(User, to_field='id', on_delete=models.CASCADE)

    def __str__(self):
        return self.name



class Issue(models.Model):
    title = models.CharField(max_length=30)
    desc = models.CharField(max_length=300)
    creator = models.ForeignKey(User, to_field='id', on_delete=models.SET_DEFAULT, default = 1, related_name='creator') #default must point to anonymous user
    assignee = models.ForeignKey(User, to_field='id', on_delete=models.SET_DEFAULT, default = 1, related_name='assignee') #default must point to admin/project manager
    opened = models.DateField(default=datetime.date.today())

    priority = models.CharField(max_length=30, choices=priority, default='low')
    status = models.CharField(max_length=30, choices=status, default='open')
    comment = models.CharField(max_length=250)
    tags = models.ManyToManyField(Tag)
    closed = models.DateField(null = True, blank = True)

    project = models.ForeignKey(Project, on_delete=models.CASCADE)
    thread = models.ForeignKey('self', related_name='child', to_field='id', on_delete=models.CASCADE, null = True, blank = True)

    def __str__(self):
        return self.title



class ProjectMember(models.Model):
    user = models.ForeignKey(User, to_field='id', on_delete=models.CASCADE)
    role = models.ForeignKey(Group, to_field='name', on_delete=models.CASCADE)
    project = models.ForeignKey(Project, to_field='id', on_delete=models.CASCADE)

    def __str__(self):
        return self.user.username

main/views.py
from django.shortcuts import render, redirect
from django.http import HttpResponse
from django.contrib.auth import login, logout, authenticate
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from .decorators import unauthenticated, allowed_users
from django.contrib.auth.models import User, Group

from django.views import generic

from .models import Project, Issue, ProjectMember, Tag
import urllib


@unauthenticated
# to avoid going back to login page again and again
def loginpage(request):

    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password1')

        user = authenticate(request, username=username, password=password)

        if user:
            login(request, user)
            if request.user.groups.exists():
                group = list(
                    request.user.groups.values_list('name', flat=True))
                for i in group:
                    if i == "Admin" or i == "Project Manager" or i == "Developer":
                        return redirect('main:projects')
                    return redirect('main:issues')
            return redirect('main:add_issue')

        messages.info(request, 'username or password incorrect')
        return redirect('main:loginpage')

    form = UserCreationForm()
    return render(request, 'main/login.html', context={'form': form})


# login_required makes sure user is logged in before viewing the following templates
@login_required(login_url='main:loginpage')
@allowed_users(allowed_roles=['Developer', 'Project Manager'])
def projects(request):
    return render(request, 'main/projects.html', context={'projects': Project.objects.all(), 'pro_mem': ProjectMember.objects.all(), 'users': User.objects.all()})


@login_required(login_url='main:loginpage')
@allowed_users(allowed_roles=['Developer', 'Project Manager'])
def issue(request, project_id):
    return render(request, 'main/issue.html', context={'projects': Project.objects.all(), 'pro_mem': ProjectMember.objects.all(), 'issues': Issue.objects.all(), 'project_id': project_id, 'users': User.objects.all()})


@login_required(login_url='main:loginpage')
def issues(request):
    return render(request, 'main/issues.html', context={'projects': Project.objects.all(), 'pro_mem': ProjectMember.objects.all(), 'issues': Issue.objects.all()})


@login_required(login_url='main:loginpage')
def add_issues(request):
    if request.method == 'POST':
        issue = Issue()
        issue.title = request.POST.get('title')
        issue.desc = request.POST.get('desc')
        issue.creator = User.objects.get(id = request.POST.get('creator'))
        issue.assignee = User.objects.get(id = request.POST.get('assignee')) 
        issue.opened = request.POST.get('opened')
        issue.priority = request.POST.get('priority')
        issue.status = request.POST.get('status')
        issue.comment = request.POST.get('comment')
        issue.project = Project.objects.get(id = request.POST.get('project'))

        project = Project.objects.get(id = issue.project.id)
        project.issues_open += 1
        project.total_issues += 1
        project.save()
            
        issue.save()
        issue.tags.add(Tag.objects.get(name = request.POST.get('tags')))

        return render(request, 'main/issues.html', context={'projects': Project.objects.all(), 'pro_mem': ProjectMember.objects.all(), 'issues': Issue.objects.all()})
    return render(request, 'main/add_issue.html', context={'projects': Project.objects.all(), 'tags':Tag.objects.all(), 'users':User.objects.all()})


def logoutpage(request):
    logout(request)
    return redirect('main:loginpage')

main/templates/main/issue.html
<header>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        .topnav {
            overflow: hidden;
            background-color: #e9f173;
        }

        .topnav a {
            float: left;
            color: black;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .topnav a.active {
            background-color: #35c1f8;
            color: white;
        }

        thead {
            background-color: #35c1f8;
            height: 7ch;
        }

        td,
        th {
            border: 5px solid #7866e0;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #e9f173;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #9bec93;
            min-width: 200px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            padding: 5px 6px;
            z-index: 1;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        h1 {
            color: #302091;
        }
    </style>

</header>
<div class="topnav">
    <a class="active" href="{% url 'main:issues' %}">Home</a>
    <a href="{% url 'main:add_issues' %}">New Issue</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
</div>
<br>
<br>
<br>
<h1>ISSUES OPEN</h1>
<div class="table-scroll">
    <table>
        <thead class="thead-row">
            <tr>
                <th>
                    <div class="dropdown">
                        <span>Title</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Description</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Created By</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Date of Creation</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Priority</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Status</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Tags</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Comment</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Assigned To</span>
                        <div class="dropdown-content">
                            <p><a href="">Filter based on this Feild</a></p>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for i in issues.all %}
            {% if project_id == i.project.id %}
            <tr>
                <td>{{i.title}}</td>
                <td>{{i.desc}}</td>
                <td>{{i.creator.first_name}} {{i.creator.last_name}}</td>
                <td>{{i.opened}}</td>
                <td>{{i.priority}}</td>
                <td>{{i.status}}</td>
                <td>
                    {% for j in i.tags.all %}
                    {{j.name}}
                    {% endfor %}
                </td>
                <td>{{i.comment}}</td>
                <td>{{i.assignee.first_name}} {{i.assignee.last_name}}</td>
            </tr>
            {% endif %}
            {% endfor %}
        </tbody>
    </table>
</div>

<br>
<br>
<br>
<br>
<br>
<br>
<br>


<h1>PROJECT DETAILS</h1>
<div class="table-scroll">
    <table>
        <thead class="thead-row">
            <tr>
                <th>
                    <div class="dropdown">
                        <span>Title</span>
                        <div class="dropdown-content">
                            <p><a href="">Get Details</a></p>
                            <p><a href="">Report</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <span>Description</span>
                </th>
                <th>
                    <span>Start Date</span>
                </th>
                <th>
                    <span>Issues Open</span>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Project Manager</span>
                        <div class="dropdown-content">
                            <p><a href="">Get Details</a></p>
                            <p><a href="">Report</a></p>
                        </div>
                    </div>
                </th>
                <th>
                    <span>Core Members</span>
                    <div class="dropdown-content">
                        <p><a href="">Get Details</a></p>
                        <p><a href="">Report</a></p>
                    </div>
</div>
</th>

</tr>
</thead>
<tbody style="height: fit-content;">
    {% for i in projects.all %}
    {% if i.id == project_id %}
    <tr>
        <td>{{i.name}}</td>
        <td>{{i.desc}}</td>
        <td>{{i.start}}</td>
        <td>{{i.issues_open}}</td>
        <td>{{i.project_manager.first_name}} {{i.project_manager.last_name}} </td>
        <td>
            {% for j in pro_mem.all %}
            <div class="dropdown">
                {% if i.id == j.project.id %}
                <b>{{j.user.first_name}} {{j.user.last_name}}</b> --> <b>{{j.role}}</b>
                {% endif %}
                <div class="dropdown-content">
                    <p>{{j.user.email}}</p>
                    <p>Last seen : {{j.user.date_joined}}</p>
                </div>
            </div><br>
            {% endfor %}
        </td>
    </tr>
    {% endif %}
    {% endfor %}
</tbody>
</table>
</div>

main/templates/main/issues.html
<header>
    <style>
        table {
            font-family: arial, sans-serif;
            border-collapse: collapse;
            width: 100%;
        }

        .topnav {
            overflow: hidden;
            background-color: #e9f173;
        }

        .topnav a {
            float: left;
            color: black;
            text-align: center;
            padding: 14px 16px;
            text-decoration: none;
            font-size: 17px;
        }

        .topnav a:hover {
            background-color: #ddd;
            color: black;
        }

        .topnav a.active {
            background-color: #35c1f8;
            color: white;
        }

        thead {
            background-color: #35c1f8;
            height: 7ch;
        }

        td,
        th {
            border: 5px solid #7866e0;
            text-align: left;
            padding: 8px;
        }

        tr:nth-child(even) {
            background-color: #e9f173;
        }

        .dropdown {
            position: relative;
            display: inline-block;
        }

        .dropdown-content {
            display: none;
            position: absolute;
            background-color: #e9f173;
            min-width: 200px;
            box-shadow: 0px 8px 16px 0px rgba(0, 0, 0, 0.2);
            padding: 5px 6px;
            z-index: 0.5;
        }

        .dropdown:hover .dropdown-content {
            display: block;
        }

        h1 {
            color: #302091;
        }
    </style>

</header>
<div class="topnav">
    <a class="active" href="{% url 'main:issues' %}">Home</a>
    <a href="{% url 'main:add_issues' %}">New Issue</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
</div>
<br>
<br>
<br>
<h1>ISSUES OPEN</h1>
<div class="table-scroll">
    <table>
        <thead class="thead-row">
            <tr>
                <th>
                    <div class="dropdown">
                        <span>Title</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Description</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Created By</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Date of Creation</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Priority</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Status</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Tags</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Comment</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Assigned To</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
                <th>
                    <div class="dropdown">
                        <span>Project</span>
                        <div class="dropdown-content">
                            <a href=""><p>Filter based on this Feild</p></a>
                        </div>
                    </div>
                </th>
            </tr>
        </thead>
        <tbody>
            {% for i in issues.all %}
            <tr>
                <td>{{i.title}}</td>
                <td>{{i.desc}}</td>
                <td>{{i.creator.first_name}} {{i.creator.last_name}}</td>
                <td>{{i.opened}}</td>
                <td>{{i.priority}}</td>
                <td>{{i.status}}</td>
                <td>
                    {% for j in i.tags.all %}
                    {{j.name}}
                    {% endfor %}
                </td>
                <td>{{i.comment}}</td>
                <td>{{i.assignee.first_name}} {{i.assignee.last_name}}</td>
                <td>{{i.project.name}}</td>
            </tr>
            {% endfor %}
        </tbody>
    </table>
</div>

main/templates/main/projects.html
{% load static from static %}

<!DOCTYPE html>
<html lang="en">

<head>
  <title>Projects</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">


  <link href="https://fonts.googleapis.com/css?family=Muli:300,400,700,900" rel="stylesheet">
  <link rel="stylesheet" href="{% static 'fonts/icomoon/style.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/jquery-ui.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.carousel.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">
  <link rel="stylesheet" href="{% static 'css/owl.theme.default.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/jquery.fancybox.min.css' %}">

  <link rel="stylesheet" href="{% static 'css/bootstrap-datepicker.css' %}">

  <link rel="stylesheet" href="{% static 'fonts/flaticon/font/flaticon.css' %}">

  <link rel="stylesheet" href="{% static 'css/aos.css' %}">
  <link href="{% static 'css/jquery.mb.YTPlayer.min.css' %}" media="all" rel="stylesheet" type="text/css">

  <link rel="stylesheet" href="{% static 'css/style.css' %}">

  <style>
    .topnav {
      overflow: hidden;
      background-color: #e9f173;
    }

    .topnav a {
      float: left;
      color: black;
      text-align: center;
      padding: 14px 16px;
      text-decoration: none;
      font-size: 17px;
    }

    .topnav a:hover {
      background-color: #ddd;
      color: black;
    }

    .topnav a.active {
      background-color: #35c1f8;
      color: white;
    }
  </style>



</head>


<body data-spy="scroll" data-target=".site-navbar-target" data-offset="300">

  <div class="topnav">
    <a class="active" href="{% url 'main:issues' %}">Home</a>
    <a href="{% url 'main:add_issues' %}">New Issue</a>
    <a href="#contact">Contact</a>
    <a href="#about">About</a>
  </div>

  <div class="site-wrap">

    <div class="site-mobile-menu site-navbar-target">
      <div class="site-mobile-menu-header">
        <div class="site-mobile-menu-close mt-3">
          <span class="icon-close2 js-menu-toggle"></span>
        </div>
      </div>
      <div class="site-mobile-menu-body"></div>
    </div>




    <div class="site-section">
      <div class="container">

        <div class="row">
          <div class="col-md-3">
            <div class="side-box mb-5">
              <h3>All Projects</h3>
              {% for i in projects.all %}
              <ul class="list-unstyled auction-categories">
                <li><a href="#">Name : <span>{{i.name}}</span></a></li>
              </ul>
              {% endfor %}
            </div>
            <div class="side-box">
              <h3>Core Project Members</h3>
            </div>
            <ul class="list-unstyled bidders">
              {% for i in users.all %}
              {% if i.username != "admin" %}
              <li class="d-flex justify-content-between align-items-center">
                <div class="d-flex align-items-center">
                  <div class="d-flex align-items-center">
                    <span>{{i.first_name}} {{i.last_name}}</span>
                  </div>
                </div>
                <span class="price">({{i.groups.first}})</span>
              </li>
              {% endif %}
              {% endfor %}

            </ul>
          </div>
          <div class="col-md-9">
            <div class="row auctions-entry">


              {% for i in pro_mem.all %}
              {% if user.id == i.user.id %}
              <div class="col-6 col-md-4 col-lg-4">
                <div class="item">
                  <div>
                    <a href="{% url 'main:issue' i.project.id %}"><img src="static/images/images.png" alt="Image"
                        class="img-fluid"></a>
                  </div>
                  <div class="p-4">
                    <h3><a href="item-single.html">Name : {{i.project.name}}</a></h3>
                    <div class="d-flex mb-2">
                      <span>Managed By : {{i.project.project_manager.first_name}}
                        {{i.project.project_manager.last_name}}</span>
                    </div>
                    <span>Issues Open : {{i.project.issues_open}} </span>
                  </div>

                </div>
              </div>
              {% endif %}
              {% endfor %}

              {% if user.username == "admin" %}
              {% for i in projects.all %}
              <div class="col-6 col-md-4 col-lg-4">
                <div class="item">
                  <div>
                    <a href="{% url 'main:issue' i.id %}"><img src="static/images/images.png" alt="Image"
                        class="img-fluid"></a>
                  </div>
                  <div class="p-4">
                    <h3><a href="item-single.html">Name : {{i.name}}</a></h3>
                    <div class="d-flex mb-2">
                      <span>Managed By : {{i.project_manager.first_name}}
                        {{i.project_manager.last_name}}</span>
                    </div>
                    <span>Issues Open : {{i.issues_open}} </span>
                  </div>

                </div>
              </div>
              {% endfor %}
              {% endif %}

            </div>
          </div>
        </div>
      </div>

      <div class="pb-5">
        <div class="container text-center">
          <div class="row">
            <div class="col-lg">
              <div class="custom-pagination">
                <a href="#" class="active">1</a>
                <a href="#">2</a>
                <a href="#">3</a>
                <a href="#">4</a>
                <a href="#">5</a>
              </div>
            </div>
          </div>
        </div>

      </div>






    </div>
    <div id="loader" class="show fullscreen"><svg class="circular" width="48px" height="48px">
        <circle class="path-bg" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke="#eeeeee" />
        <circle class="path" cx="24" cy="24" r="22" fill="none" stroke-width="4" stroke-miterlimit="10"
          stroke="#51be78" /></svg></div>

    <script src="static/js/jquery-3.3.1.min.js"></script>
    <script src="static/js/jquery-migrate-3.0.1.min.js"></script>
    <script src="static/js/jquery-ui.js"></script>
    <script src="static/js/popper.min.js"></script>
    <script src="static/js/bootstrap.min.js"></script>
    <script src="static/js/owl.carousel.min.js"></script>
    <script src="static/js/jquery.stellar.min.js"></script>
    <script src="static/js/jquery.countdown.min.js"></script>
    <script src="static/js/bootstrap-datepicker.min.js"></script>
    <script src="static/js/jquery.easing.1.3.js"></script>
    <script src="static/js/aos.js"></script>
    <script src="static/js/jquery.fancybox.min.js"></script>
    <script src="static/js/jquery.sticky.js"></script>
    <script src="static/js/jquery.mb.YTPlayer.min.js"></script>




    <script src="static/js/main.js"></script>

</body>

</html>